export const RECIPES_FROM_INGREDIENTS = 'RECIPES_FROM_INGREDIENTS';
export const SET_CURRENT_RECIPE_INGREDIENTS = 'SET_CURRENT_RECIPE_INGREDIENTS';
export const SET_CURRENT_RECIPE_INSTRUCTIONS = 'SET_CURRENT_RECIPE_INSTRUCTIONS';