export const RECIPES_FROM_INGREDIENTS = 'RECIPES_FROM_INGREDIENTS';
export const SET_ACTIVE_RECIPE_INGREDIENTS = 'SET_ACTIVE_RECIPE_INGREDIENTS';
export const SET_ACTIVE_RECIPE_INSTRUCTIONS = 'SET_ACTIVE_RECIPE_INSTRUCTIONS';